# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem 'appium_lib', '~> 9.8', '>= 9.8.1'
gem 'capybara', '~> 2.16', '>= 2.16.1'
gem 'rspec', '~> 3.7'