# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem 'appium_lib', '~> 9.8', '>= 9.8.1'
gem 'capybara', '~> 2.16', '>= 2.16.1'
gem 'cucumber', '~> 2.4'
gem 'test-unit', '~> 3.2', '>= 3.2.7'
gem 'sauce_whisk', '~> 0.1.0'
gem 'rest-client', '~> 2.0', '>= 2.0.2'
gem 'spec', '~> 5.3', '>= 5.3.4'
gem 'rspec', '~> 3.7'
gem 'rspec-expectations', '~> 3.7'
gem 'selenium-webdriver', '~> 3.8'
gem 'touch_action', '~> 1.3', '>= 1.3.3'
gem 'watir', '~> 6.10', '>= 6.10.2'