# frozen_string_literal: true

source "https://rubygems.org"
#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'appium_lib',         '~> 9.7.4'
gem 'rest-client',        '~> 2.0.2'
gem 'rspec',              '~> 3.7.0'
gem 'touch_action',       '~> 1.3'
gem 'cucumber',           '~> 2.4.0'
gem 'capybara',           '~> 2.16'
gem 'rspec-expectations', '~> 3.7.0'
gem 'spec',               '~> 5.3.4'
gem 'sauce_whisk',        '~> 0.0.13'
gem 'test-unit',          '~> 2.5.5' # required for bundle exec ruby xunit_android.rb


